package org.motus.common

public enum AccoladePoints {

	LOGGED_WORKOUT(6),
	LOGGED_XSTRETCH(4),
	LOGGED_YOGAX(8),
	COMPLETED_AB_RIPPER(2),
	PERFECT_WEEK(30),	
	TWENTY_MINUTE_CARDIO(2),
	THIRTY_MINUTE_CARDIO(3),
	FORTY_MINUTE_CARDIO(4),
	FIFTY_MINUTE_CARDIO(5),
	SIXTY_MINUTE_CARDIO(6),
	SEVENTY_MINUTE_CARDIO(7),
	EIGHTY_MINUTE_CARDIO(8),
	NINETY_MINUTE_CARDIO(9),
	TWENTY_MINUTE_FREEWEIGHTS(2),
	THIRTY_MINUTE_FREEWEIGHTS(3),
	FORTY_MINUTE_FREEWEIGHTS(4),
	FIFTY_MINUTE_FREEWEIGHTS(5),
	SIXTY_MINUTE_FREEWEIGHTS(6),
	SEVENTY_MINUTE_FREEWEIGHTS(7),
	EIGHTY_MINUTE_FREEWEIGHTS(8),
	NINETY_MINUTE_FREEWEIGHTS(9),
	PROGRAM_COMPLETE(50),
	PERFECT_PROGRAM(100),
	PHOTO_UPLOADED(5),	
	PARTICIPATED_COMPETITION(15),
	FIRST_PLACE_COMPETITION(50),
	SECOND_PLACE_COMPETITION(40),
	THIRD_PLACE_COMPETITION(30)
	
	private final int value
	
	AccoladePoints(int value){
		this.value = value
	}
	
	public int value(){
		return this.value
	}

}