package org.motus.common

public enum AccoladeType {

	LOGGED_WORKOUT('LOGGED_WORKOUT'),
	LOGGED_XSTRETCH('LOGGED_XSTRETCH'),
	LOGGED_YOGAX('LOGGED_YOGAX'),
	COMPLETED_AB_RIPPER('COMPLETED_AB_RIPPER'),
	PERFECT_WEEK('PERFECT_WEEK'),
	TWENTY_MINUTE_CARDIO('TWENTY_MINUTE_CARDIO'),
	THIRTY_MINUTE_CARDIO('THIRTY_MINUTE_CARDIO'),
	FORTY_MINUTE_CARDIO('FORTY_MINUTE_CARDIO'),
	FIFTY_MINUTE_CARDIO('FIFTY_MINUTE_CARDIO'),
	SIXTY_MINUTE_CARDIO('SIXTY_MINUTE_CARDIO'),
	SEVENTY_MINUTE_CARDIO('SEVENTY_MINUTE_CARDIO'),
	EIGHTY_MINUTE_CARDIO('EIGHTY_MINUTE_CARDIO'),
	NINETY_MINUTE_CARDIO('NINETY_MINUTE_CARDIO'),
	TWENTY_MINUTE_FREEWEIGHTS('TWENTY_MINUTE_FREEWEIGHTS'),
	THIRTY_MINUTE_FREEWEIGHTS('THIRTY_MINUTE_FREEWEIGHTS'),
	FORTY_MINUTE_FREEWEIGHTS('FORTY_MINUTE_FREEWEIGHTS'),
	FIFTY_MINUTE_FREEWEIGHTS('FIFTY_MINUTE_FREEWEIGHTS'),
	SIXTY_MINUTE_FREEWEIGHTS('SIXTY_MINUTE_FREEWEIGHTS'),
	SEVENTY_MINUTE_FREEWEIGHTS('SEVENTY_MINUTE_FREEWEIGHTS'),
	EIGHTY_MINUTE_FREEWEIGHTS('EIGHTY_MINUTE_FREEWEIGHTS'),
	NINETY_MINUTE_FREEWEIGHTS('NINETY_MINUTE_FREEWEIGHTS'),
	PROGRAM_COMPLETE('PERFECT_PROGRAM'),
	PERFECT_PROGRAM('PERFECT_PROGRAM'),
	PHOTO_UPLOADED('PHOTO_UPLOADED'),
	PARTICIPATED_COMPETITION('PARTICIPATED_COMPETITION'),
	FIRST_PLACE_COMPETITION('FIRST_PLACE_COMPETITION'),
	SECOND_PLACE_COMPETITION('SECOND_PLACE_COMPETITION'),
	THIRD_PLACE_COMPETITION('THIRD_PLACE_COMPETITION')
	
	private final String description
	
	AccoladeType(String description){
		this.description = description
	}
	
	public String description(){
		return this.description
	}
	
}
